In [21]:
#Basic mathematical operations
import numpy as np
array=np.array([1,3,5,7,9,11])
print("Multiplication:",array*2)
print("Division      :",array/2)
print("Addition      :",array+1)
print("Subtraction   :",array-1)

Multiplication: [ 2  6 10 14 18 22]
Division      : [0.5 1.5 2.5 3.5 4.5 5.5]
Addition      : [ 2  4  6  8 10 12]
Subtraction   : [ 0  2  4  6  8 10]


In [22]:
#Size and shape
size=array.size
shape=array.shape
print(size)
print(shape)

6
(6,)


In [23]:
#Reshaping of array
reshaped_array=array.reshape(3,2)
print("array:",array)
print("-"*20)
print("reshaped array:")
print(reshaped_array)

array: [ 1  3  5  7  9 11]
--------------------
reshaped array:
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [24]:
#Accessing elements using Index
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array[2]) 


3


In [25]:
#Accessing Elements
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array[0:4])

[1 2 3 4]


In [26]:
#Reversing an array
print("Array",numpy_array)
print("Reversed Array",numpy_array[::-1])

Array [1 2 3 4 5 6 7 8 9]
Reversed Array [9 8 7 6 5 4 3 2 1]


In [29]:
#Aggregation(Min,Max,Sum)
print("Max   :",numpy_array.max())
print("Min   :",numpy_array.min())
print("Sum   :",numpy_array.sum())
print("Median:",np.median(numpy_array))

Max   : 9
Min   : 1
Sum   : 45
Median: 5.0


In [11]:
#Central quatitities
print("Mean         :",numpy_array.mean())
print("Varriance    :",numpy_array.var())
print("Std Deviation:",numpy_array.std())

Mean         : 5.0
Varriance    : 6.666666666666667
Std Deviation: 2.581988897471611


In [12]:
#Operations on rows and columns using axis
numpy_matrix = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
numpy_matrix = numpy_matrix.reshape(4, 2)
print(numpy_matrix)
print("-"*20)
print(numpy_matrix.sum(axis = 0))
print("-"*20)
print(numpy_matrix.sum(axis = 1))
print("-"*20)
print(numpy_matrix.sum(axis = None))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------
[16 20]
--------------------
[ 3  7 11 15]
--------------------
36


In [13]:
#Joining arrays
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])
print(np.concatenate((array_1, array_2, array_3)))    
array_4 = np.array([[1,2,3],[0,0,0]])
array_5 = np.array([[0,0,0],[7,8,9]])
print(np.concatenate((array_4, array_5),axis=1))   

[1 2 3 4 5 6 7 8 9]
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [14]:
#Arrays with zeroes
print(np.zeros((1,2)))                   
print(np.zeros((1,2), dtype = np.int)) 

[[0. 0.]]
[[0 0]]


In [15]:
#Arrays with ones
print(np.ones((1,2)))                   
print(np.ones((1,2), dtype = np.int))

[[1. 1.]]
[[1 1]]


In [16]:
#Identity and Eye Matrix
print(np.identity(3))
print("-"*20)
print(np.eye(8, 7, k = 1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
#Multiplying Matri
array_6 = np.array([ 1, 2 ])
array_7 = np.array([ 3, 4 ])
print("Dot Product  :",np.dot(array_6, array_7))
print("Cross Product:",np.cross(array_6, array_7))      

Dot Product  : 11
Cross Product: -2


In [32]:
#Arrange Function
arr1d = np.arange(5)
print(arr1d)
print("-"*20)
arr1d = np.arange(0, 12, 2)
print(numpy_array)
print("-"*20)
arr2d = np.arange(0, 12, 2).reshape(2, 3)
print(arr2d) 

[0 1 2 3 4]
--------------------
[1 2 3 4 5 6 7 8 9]
--------------------
[[ 0  2  4]
 [ 6  8 10]]


In [33]:
#Elementary mathematical operations
#Elementary Mathematical Functions 

arr2d = np.array([[10, 20, 30], [40, 50, 60]])

print(np.sin(arr2d))
print("-" * 40)
 
print(np.cos(arr2d))
print("-" * 40)
 
print(np.tan(arr2d))
print("-" * 40)
 
print(np.sqrt(arr2d))
print("-" * 40)
 
print(np.exp(arr2d))
print("-" * 40)
 
print(np.log10(arr2d))
print("-" * 40)

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]
----------------------------------------
[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]
----------------------------------------
[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]
----------------------------------------
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
----------------------------------------
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]
----------------------------------------
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
----------------------------------------


In [36]:
#Random Number Array
print(np.random.rand(3, 2))  # Uniformly distributed values.
print("-"*20)
print(np.random.randn(3, 2))  # Normally distributed values.
print("-"*20)
print("-"*20)
# Uniformly distributed integers in a given range.
print(np.random.randint(2, size=10)) #range is 0-2
print("-"*20)
print(np.random.randint(5, size=(2, 4))) #range is 0-5

[[0.63479487 0.45522839]
 [0.36236428 0.16512442]
 [0.13561867 0.3011773 ]]
--------------------
[[-0.13615479 -0.92862273]
 [ 0.26136686 -0.51833194]
 [ 0.24262491  0.51039654]]
--------------------
--------------------
[0 0 1 0 0 0 1 0 0 0]
--------------------
[[1 2 1 2]
 [4 2 1 1]]
